# Generated by Django 4.1.4 on 2022-12-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_ports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='boatDeep',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='boatLenght',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='boatWidth',
            field=models.PositiveIntegerField(),
        ),
    ]
